### ISSUE TITLE
Import don't work

### ISSUE THREAD

**Issue by DigiTamerFun** [armory3d/armorpaint#257]
*ArmorPaint 0.7-10c63f2, Windows*

I want to import texture and mesh files. When importing textures, empty material is created. Meshes are not displayed.

**Comment by luboslenco** [comment]
Thanks for report, investigating. Will report back!

**Comment by Calpal3D** [comment]
Same problem here. I just downloaded armor paint and I can't import meshes. I tried a simple mesh as an fbx and obj with UVs.

**Comment by luboslenco** [comment]
Are there any accented characters in the path from where the mesh is loaded (or in the mesh name itself)? Does loading from path like `C:\Assets\mesh.obj` (just for testing) work?

Paths with accented characters are supposed to work as well, but looks like something is acting up. Also, am I correct to assume this is Windows 10?

**Comment by Calpal3D** [comment]
Thanks! it works now. I tried to load it off our server and that didn't work. I copied it to the desktop and now it works.

**Comment by luboslenco** [comment]
Great to hear! Looking into a fix now, will push updated builds asap.

**Comment by Calpal3D** [comment]
Thank you

**Comment by luboslenco** [comment]
Any luck using the newly updated 0.8 dev builds? Does import/export work correctly?

**Comment by Calpal3D** [comment]
thanks for checking it out. Import ant exporting meshes works fine. But exporting textures doesn't work in the latest build im using. 08dev build

**Comment by luboslenco** [comment]
Can you paste `stderr.txt` file from your `\ArmorPaint` folder (if present) here?
Are you able to share the path where your ArmorPaint copy is unpacked (eg. `C:\Programs\ArmorPaint`)? 
Hopefully I will be able to reproduce and fix. Thanks for help!

**Comment by Calpal3D** [comment]
my armor paint is in here:
C:\Program Files\ArmorPaint
Where can I find the stderr.txt file?

**Comment by luboslenco** [comment]
Aha, Windows may prevent ArmorPaint from writing files in there. As a workaround it should work if you move it to `Documents`/`Downloads` folder or similar where file writing is not restricted.

Will push another fix in upcoming builds to make it work from the `Program Files` folder as well. :)

**Comment by luboslenco** [comment]
Network paths and placing ArmorPaint into `Program Files` should now work in updated 0.8 dev builds.

**Comment by luboslenco** [comment]
Please reopen if issue persists.

**Comment by 2w6t9gl5** [comment]
I just tried to import a mesh and the program stalls. I have the program in the Program Files folder and tried to import the mesh from c:/armourpaintassets  . I'm using the ArmorPaint_08dev_win64.zip on windows 10

**Comment by luboslenco** [comment]
@2w6t9gl5 sorry but I need more info to be helpful - can you share the mesh file which stalls?

**Comment by 2w6t9gl5** [comment]
I have tried several files and they all fail. This was the last one I tried.

**Comment by 2w6t9gl5** [comment]
Hi Lubos, I posted the file on github, do you need to see any other meshes?

 

Thanks,

Barry

**Comment by 2w6t9gl5** [comment]
I tried importing the  test obj files into Meshlab where it noted errors. I then saved and exported and the file imports into Armourpaint. Could be an older version of obj file causes issues.

**Comment by luboslenco** [comment]
Happy to hear! I also pushed a fix at https://github.com/armory3d/armorpaint/commit/988af9afd2783816cc1b88a8b2180b88d02e6f14, so ArmorPaint will properly parse your original files as well. Will upload new builds tomorrow. Also note that the uv map should have no overlapping faces for painting, please see [here](https://github.com/armory3d/armorpaint_docs/blob/master/faq.md#mesh-gets-painted-on-multiple-places-at-once) for more info.

**Comment by FellipePeixoto** [comment]
Import doens't here too. When I try to import some texture the armorpaint closes.

The **stderr.txt** is a log file? I searched for that file but I don't found. I changed the armorpaint location for another directory (no protected), but the problem persists.

_Windows 10 - ArmorPaint.org - v0.8 (2021-04-01) - 7b1fdcf_
